import LocalizedStrings from 'localized-strings';

export function getCulture(): string {
	const urlParams = new URLSearchParams(window.location.search);
	return urlParams.get('culture') || '';
}

const localization = new LocalizedStrings({
	en: {
		aboutMyself: 'Vladimir Khil',
		aboutMyselfText: 'Hi! I\'m a passionate software developer and mathematician who loves creating innovative solutions. I specialize in building applications that make complex tasks simple and enjoyable.',
		aboutTheAuthor: 'About the Author',
		andLater: 'and later',
		blog: 'Blog',
		buildTransformTable: 'Ganarate transformation table',
		classicTransform: 'Classic transform',
		currentPositionText: 'Currently working as a team lead, helping teams build amazing software while continuing to code and learn new technologies.',
		details: 'Details',
		donateBoostyDescription: 'Support me on the Russian platform Boosty with flexible payment options and exclusive content for subscribers.',
		donateExplanation: 'I\'m developing SIGame and related projects, and also spend my own money to support the game server and domain. Your support helps me continue creating and maintaining these free tools for the community.',
		donatePatreonDescription: 'Support my ongoing development work with monthly contributions. Get access to exclusive updates and early previews of new features.',
		donateSupport: 'Support via',
		donateThankYou: 'Thank you for your support! Every contribution helps me dedicate more time to improving SIGame and creating new features.',
		donateTitle: 'Support My Work',
		donateYooMoneyDescription: 'Make a one-time donation via YooMoney to help cover server costs and development expenses.',
		educationText: 'I graduated with honors from MAI (Moscow Aviation Institute) with degrees in mathematics and computer science.',
		experienceText: 'I work primarily with .NET technologies and have extensive experience in C#, TypeScript, and modern web development. I enjoy working on everything from desktop applications to web platforms, always focusing on clean code and great user experiences.',
		familyNotFound: 'App not found',
		files: 'Files',
		friendLinkAlexandrProsvirnov: 'Alexandr Prosvirnov about his participation in "Svoya Igra" tv show (Russian)',
		friendLinkAlexUtah: '"Svoya Igra" through the eyes of Alexander Uspanov (Russian)',
		friendLinkGameShows: 'GameShows — Everything about TV games (Russian)',
		friendLinks: 'Friend links',
		friendLinkSI: '"Svoya Igra": database of players and games, history and statistics (Russian)',
		games: 'Games',
		generateSourceCode: 'Generate source code',
		githubProfile: 'View my projects on GitHub',
		hint: 'You can tranform input text with the SPARD language rules described here.',
		home: 'Home',
		latestNews: 'Latest news',
		myPhotos: 'My photos',
		news: 'News',
		noEntries: 'No entries found',
		products: 'Products',
		profileBio: 'Developer, lover of intellectual games, traveler and just an adventurer',
		readingTime: 'Reading time {0} min',
		search: 'Search',
		siGameDescription: 'Play as a real player, host, or spectator in an exciting intellectual game',
		siQuesterDescription: 'Create and edit question packages for SIGame',
		siSimulatorDescription: 'Offline mode for SIGame — play without a network connection',
		circeDescription: 'An IRC client with a modern interface',
		spardDescription: 'A language for text pattern matching and transformation',
		supportFinancially: 'Support financially',
		inputText: 'Input text',
		install: 'Install',
		isClassicResultNotTheSame: 'Classic transform got the same result',
		isClassicResultTheSame: 'Classic transform got different result',
		knownIssues: 'Known issues',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		newsForTheYear: 'News for the {0} year',
		projectsText: 'I\'ve created various projects including quiz games, language processing tools, and educational applications. I also developed my own programming language called SPARD for text transformations.',
		releaseHistory: 'Release history',
		result: 'Result',
		screenshots: 'Screenshots',
		selectExample: 'Select an example…',
		selectFile: 'Select file…',
		spardInterpreter: 'SPARD Interpreter',
		spardIntroduction: 'Introduction to SPARD',
		spardSpecification: 'SPARD Language Specification',
		spardTableDescription: 'This transformer works with SPARD subset - SPARD Lite which includes symbols, strings and operators |, _, $, :: и =>.',
		spardTableHint: 'Is is equal to the classic (tree-based) SPARD-transformer but has a bigger performance. But additional time for building it is required.',
		spardTableTransformer: 'SPARD table transformer',
		spardTransformer: 'SPARD transformer',
		tableTransform: 'Table transform',
		tags: 'Tags',
		transform: 'Transform',
		transformationRules: 'Transformation rules (SPARD)',
		transformationRulesLight: 'Transformation rules (SPARD Lite)',
		transformationTime: 'transformation time',
		tvGameChgkDf: '"What? Where? When?" by Danil Fedorovih (Russian)',
		tvGamesHeader: 'TV Game Computer Analogues (Russian)',
		tvGameMillionErudit: '"Who Wants to Be a Millionaire?" by L.I. Fedorchuk (Russian)',
		tvGameMillionOhLucky: '"Who Wants to Be a Millionaire?" (unknown author) (Russian)',
		tvGameMillionOhLucky2: '"Who Wants to Be a Millionaire?" by Vladimir Khil (Russian)',
		tvGameMillionTvgame: 'Multiple versions of "Who Wants to Be a Millionaire?" (Russian)',
		tvGamePoleChudesOnline: 'Online game "Field of Miracles" (Russian)',
		tvGameRussianRoulette: 'Computer game "Russian Roulette" by Sergey Boytsov & Co (Russian)',
		tvGameSlaboeZvenoApteka: '"Weakest Link" by Multifox (Alexey Romanov) (Russian)',
		tvGameSvoyaIgra: 'Computer "Svoya Igra" by Maxim Kishkevich (Russian)',
		tvGameTheSmartest: '"Who is the Smartest?" by comulti multimedia (Russian)',
		tvGameUgadajMelodiju: 'Computer game "Guess the Melody" by Dmitry Sharov (Russian)',
		upload: 'Upload…',
		version: 'Version',
		webBrowser: 'Web browser',
		websiteNews: 'Website news',
	},
	ru: {
		aboutMyself: 'Владимир Хиль',
		aboutMyselfText: 'Привет! Я увлеченный разработчик программного обеспечения и математик, который любит создавать инновационные решения. Специализируюсь на создании приложений, которые делают сложные задачи простыми и приятными.',
		aboutTheAuthor: 'Об авторе',
		andLater: 'и выше',
		blog: 'Блог',
		buildTransformTable: 'Составить таблицу переходов',
		classicTransform: 'Классическое преобразование',
		currentPositionText: 'В настоящее время работаю тимлидом, помогая командам создавать удивительное программное обеспечение, продолжая при этом программировать и изучать новые технологии.',
		details: 'Описание',
		donateBoostyDescription: 'Поддержите меня на российской платформе Boosty с гибкими вариантами оплаты и эксклюзивным контентом для подписчиков.',
		donateExplanation: 'Я разрабатываю SIGame и связанные проекты, а также трачу собственные средства на поддержку игрового сервера и домена. Ваша поддержка помогает мне продолжать создавать и поддерживать эти бесплатные инструменты для сообщества.',
		donatePatreonDescription: 'Поддержите мою работу с помощью ежемесячных взносов. Получите доступ к эксклюзивным обновлениям и ранним превью новых функций.',
		donateSupport: 'Поддержать через',
		donateThankYou: 'Спасибо за вашу поддержку! Каждый вклад помогает мне уделять больше времени улучшению SIGame и созданию новых функций.',
		donateTitle: 'Поддержите мою работу',
		donateYooMoneyDescription: 'Сделайте разовое пожертвование через YooMoney, чтобы помочь покрыть расходы на сервер и разработку.',
		educationText: 'Окончил с отличием МАИ (Московский авиационный институт) по специальностям математика и информатика.',
		experienceText: 'Работаю преимущественно с технологиями .NET и имею обширный опыт в C#, TypeScript и современной веб-разработке. Мне нравится работать над всем — от настольных приложений до веб-платформ, всегда фокусируясь на чистом коде и отличном пользовательском опыте.',
		familyNotFound: 'Приложение не найдено',
		files: 'Файлы',
		friendLinkAlexandrProsvirnov: 'Александр Просвирнов о своём участии в «Своей игре»',
		friendLinkAlexUtah: '«Своя игра» глазами Александра Успанова',
		friendLinkGameShows: 'GameShows — Всё о телеиграх',
		friendLinks: 'Дружественные ссылки',
		friendLinkSI: '«Своя игра»: база данных игроков и игр, история и статистика',
		games: 'Игры',
		generateSourceCode: 'Создать код',
		githubProfile: 'Посмотреть мои проекты на GitHub',
		hint: 'На этой странице можно осуществить преобразование входного текста в соответствии с заданными правилами преобразования (на языке SPARD).',
		home: 'Главная',
		latestNews: 'Последние новости',
		myPhotos: 'Мои фотографии',
		news: 'Новости',
		noEntries: 'Записи не найдены',
		products: 'Продукты',
		profileBio: 'Программист, любитель интеллектуальных игр, путешественник и просто искатель приключений',
		readingTime: 'Время чтения {0} мин',
		search: 'Поиск',
		siGameDescription: 'Почувствуйте себя настоящим игроком, ведущим или зрителем в увлекательной интеллектуальной игре',
		siQuesterDescription: 'Создавайте и редактируйте пакеты вопросов для SIGame',
		siSimulatorDescription: 'Офлайн-режим для SIGame — играйте без сетевого подключения',
		circeDescription: 'IRC-клиент с современным интерфейсом',
		spardDescription: 'Язык для сопоставления и преобразования текстовых шаблонов',
		supportFinancially: 'Помочь материально',
		inputText: 'Входной текст',
		install: 'Установить',
		isClassicResultNotTheSame: 'классический преобразователь дал другой результат',
		isClassicResultTheSame: 'классический преобразователь дал такой же результат',
		knownIssues: 'Известные проблемы и решения',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		newsForTheYear: 'Новости за {0} год',
		projectsText: 'Создал различные проекты, включая викторины, инструменты обработки языков и образовательные приложения. Также разработал собственный язык программирования SPARD для трансформации текстов.',
		releaseHistory: 'История версий',
		result: 'Результат',
		screenshots: 'Галерея',
		selectExample: 'Выберите пример…',
		selectFile: 'Выберите файл…',
		spardInterpreter: 'Интерпретатор SPARD',
		spardIntroduction: 'Введение в SPARD',
		spardSpecification: 'Спецификация языка SPARD',
		spardTableDescription: 'Преобразователь работает на подмножестве SPARD - SPARD Lite, включающем в себя символы, строки и операции |, _, $, :: и =>.',
		spardTableHint: 'Аналогичен классическому (древовидному) SPARD-преобразователю, но работает более эффективно. При этом затрачивается дополнительное время на его построение.',
		spardTableTransformer: 'Табличный преобразователь SPARD',
		spardTransformer: 'Преобразователь SPARD',
		tableTransform: 'Табличное преобразование',
		tags: 'Теги',
		transform: 'Преобразовать',
		transformationRules: 'Правила преобразования (SPARD)',
		transformationRulesLight: 'Правила преобразования (SPARD Lite)',
		transformationTime: 'время преобразования',
		tvGameChgkDf: '«Что? Где? Когда?» (автор — Данил Фёдоровых)',
		tvGamesHeader: 'Компьютерные аналоги телевизионных игр',
		tvGameMillionErudit: '«Кто хочет стать миллионером?» (автор — Л.И. Федорчук)',
		tvGameMillionOhLucky: '«Кто хочет стать миллионером?» (автор неизвестен)',
		tvGameMillionOhLucky2: '«Кто хочет стать миллионером?» (автор — Владимир Хиль)',
		tvGameMillionTvgame: 'Множественные версии «Кто хочет стать миллионером?»',
		tvGamePoleChudesOnline: 'Онлайн-игра «Поле Чудес»',
		tvGameRussianRoulette: 'Компьютерная игра «Русская рулетка» (автор - Сергей Бойцов и Ко)',
		tvGameSlaboeZvenoApteka: '«Слабое звено» от Multifox (Алексей Романов)',
		tvGameSvoyaIgra: 'Компьютерная «Своя игра» (автор — Максим Кишкевич)',
		tvGameTheSmartest: '«Кто самый умный?» от comulti multimedia',
		tvGameUgadajMelodiju: '«Угадай мелодию» (автор — Дмитрий Шаров)',
		upload: 'Загрузить…',
		version: 'Версия',
		webBrowser: 'Веб-браузер',
		websiteNews: 'Новости сайта',
	},
	sr: {
		aboutMyself: 'Vladimir Hil',
		aboutMyselfText: 'Zdravo! Ja sam strastveni programer i matematičar koji voli da kreira inovativna rešenja. Specijalizujem se za kreiranje aplikacija koje kompleksne zadatke čine jednostavnim i prijatnim.',
		aboutTheAuthor: 'O autoru',
		andLater: 'i noviji',
		blog: 'Blog',
		buildTransformTable: 'Generiši tabelu transformacije',
		classicTransform: 'Klasična transformacija',
		currentPositionText: 'Trenutno radim kao team lead, pomažem timovima da prave neverojan softver dok nastavljam da kodiram i učim nove tehnologije.',
		details: 'Detalji',
		donateBoostyDescription: 'Podržite me na ruskoj platformi Boosty sa fleksibilnim opcijama plaćanja i ekskluzivnim sadržajem za pretplatnike.',
		donateExplanation: 'Razvijam SIGame i povezane projekte, a takođe trošim sopstveni novac za podršku game servera i domene. Vaša podrška mi pomaže da nastavim sa kreiranjem i održavanjem ovih besplatnih alata za zajednicu.',
		donatePatreonDescription: 'Podržite moj rad kroz mesečne doprinose. Dobijte pristup ekskluzivnim ažuriranjima i ranim pregledima novih funkcija.',
		donateSupport: 'Podržite preko',
		donateThankYou: 'Hvala vam na podršci! Svaki doprinos mi pomaže da posvetim više vremena poboljšanju SIGame-a i kreiranju novih funkcija.',
		donateTitle: 'Podržite moj rad',
		donateYooMoneyDescription: 'Napravite jednokratnu donaciju preko YooMoney da pomognete pokriti troškove servera i razvoja.',
		educationText: 'Diplomirao sam sa počastima na MAI (Moskovski avijaciski institut) sa diplomama iz matematike i računarstva.',
		experienceText: 'Radim prvenstveno sa .NET tehnologijama i imam obimno iskustvo u C#, TypeScript-u i modernom web razvoju. Uživam da radim na svemu - od desktop aplikacija do web platformi, uvek se fokusirajući na čist kod i odličan korisnički doživljaj.',
		familyNotFound: 'Aplikacija nije pronađena',
		files: 'Fajlovi',
		friendLinkAlexandrProsvirnov: 'Aleksandar Prosvirnov o svom učešću u "Svojoj igri" (ruski)',
		friendLinkAlexUtah: '"Svoja igra" očima Aleksandra Uspanova (ruski)',
		friendLinkGameShows: 'GameShows — Sve o TV igrama (ruski)',
		friendLinks: 'Prijateljski linkovi',
		friendLinkSI: '"Svoja igra": baza podataka igrača i igara, istorija i statistike (ruski)',
		games: 'Igre',
		generateSourceCode: 'Generiši izvorni kod',
		githubProfile: 'Pogledajte moje projekte na GitHub-u',
		hint: 'Možete transformisati ulazni tekst sa SPARD jezičkim pravilima opisanim ovde.',
		home: 'Početna',
		latestNews: 'Najnovije vesti',
		myPhotos: 'Moje fotografije',
		news: 'Vesti',
		noEntries: 'Nema pronađenih unosa',
		products: 'Proizvodi',
		profileBio: 'Programer, ljubitelj intelektualnih igara, putnik i prosto tragač za avanturama',
		readingTime: 'Vreme čitanja {0} min',
		search: 'Pretraga',
		siGameDescription: 'Igrajte kao pravi igrač, voditelj ili gledalac u uzbudljivoj intelektualnoj igri',
		siQuesterDescription: 'Kreirajte i uređujte pakete pitanja za SIGame',
		siSimulatorDescription: 'Offline režim za SIGame — igrajte bez mrežne veze',
		circeDescription: 'IRC klijent sa modernim interfejsom',
		spardDescription: 'Jezik za uparivanje i transformaciju tekstualnih obrazaca',
		supportFinancially: 'Finansijska podrška',
		inputText: 'Ulazni tekst',
		install: 'Instaliraj',
		isClassicResultNotTheSame: 'Klasična transformacija je dala isti rezultat',
		isClassicResultTheSame: 'Klasična transformacija je dala drugačiji rezultat',
		knownIssues: 'Poznati problemi',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		newsForTheYear: 'Vesti za {0} godinu',
		projectsText: 'Kreirao sam različite projekte uključujući kviz igre, alate za obradu jezika i edukacione aplikacije. Takođe sam razvio svoj programski jezik SPARD za transformacije teksta.',
		releaseHistory: 'Istorija izdanja',
		result: 'Rezultat',
		screenshots: 'Snimci ekrana',
		selectExample: 'Izaberite primer…',
		selectFile: 'Izaberite fajl…',
		spardInterpreter: 'SPARD Interpreter',
		spardIntroduction: 'Uvod u SPARD',
		spardSpecification: 'SPARD jezička specifikacija',
		spardTableDescription: 'Ovaj transformator radi sa SPARD podskupom - SPARD Lite koji uključuje simbole, stringove i operatore |, _, $, :: i =>.',
		spardTableHint: 'Ekvivalentan je klasičnom (tree-based) SPARD-transformatoru ali ima veće performanse. Međutim, potrebno je dodatno vreme za njegovo kreiranje.',
		spardTableTransformer: 'SPARD tabelarni transformator',
		spardTransformer: 'SPARD transformator',
		tableTransform: 'Tabelarna transformacija',
		tags: 'Oznake',
		transform: 'Transformiši',
		transformationRules: 'Pravila transformacije (SPARD)',
		transformationRulesLight: 'Pravila transformacije (SPARD Lite)',
		transformationTime: 'vreme transformacije',
		tvGameChgkDf: '"Šta? Gde? Kada?" od Danil Fedorovih (ruski)',
		tvGamesHeader: 'Računarski analozi TV igara (ruski)',
		tvGameMillionErudit: '"Ko želi da bude milioner?" od L.I. Fedorčuk (ruski)',
		tvGameMillionOhLucky: '"Ko želi da bude milioner?" (nepoznat autor) (ruski)',
		tvGameMillionOhLucky2: '"Ko želi da bude milioner?" od Vladimir Hil (ruski)',
		tvGameMillionTvgame: 'Višestruke verzije "Ko želi da bude milioner?" (ruski)',
		tvGamePoleChudesOnline: 'Online igra "Polje čudesa" (ruski)',
		tvGameRussianRoulette: 'Računarska igra "Ruska ruleta" od Sergej Bojcov & Co (ruski)',
		tvGameSlaboeZvenoApteka: '"Najslabija karika" od Multifox (Aleksej Romanov) (ruski)',
		tvGameSvoyaIgra: 'Računarska "Svoja igra" od Maksim Kiškevič (ruski)',
		tvGameTheSmartest: '"Ko je najpametniji?" od comulti multimedia (ruski)',
		tvGameUgadajMelodiju: 'Računarska igra "Pogodi melodiju" od Dmitrij Šarov (ruski)',
		upload: 'Otpremi…',
		version: 'Verzija',
		webBrowser: 'Web browser',
		websiteNews: 'Vesti sajta',
	}
},
{
	customLanguageInterface: getCulture
});

export default localization;
