import LocalizedStrings from 'localized-strings';

export function getCulture(): string {
	const urlParams = new URLSearchParams(window.location.search);
	return urlParams.get('culture') || '';
}

const localization = new LocalizedStrings({
	en: {
		andLater: 'and later',
		blog: 'Blog',
		buildTransformTable: 'Ganarate transformation table',
		classicTransform: 'Classic transform',
		details: 'Details',
		hint: 'You can tranform input text with the SPARD language rules described here.',
		inputText: 'Input text',
		install: 'Install',
		isClassicResultNotTheSame: 'Classic transform got the same result',
		isClassicResultTheSame: 'Classic transform got different result',
		familyNotFound: 'App not found',
		files: 'Files',
		friendLinkAlexandrProsvirnov: 'Alexandr Prosvirnov about his participation in “Svoya Igra” tv show (Russian)',
		friendLinkAlexUtah: '“Svoya Igra” through the eyes of Alexander Uspanov (Russian)',
		friendLinkGameShows: 'GameShows — Everything about TV games (Russian)',
		friendLinks: 'Friend links',
		friendLinkSI: '“Svoya Igra”: database of players and games, history and statistics (Russian)',
		generateSourceCode: 'Generate source code',
		home: 'Home',
		knownIssues: 'Known issues',
		languageEn: 'English',
		languageRu: 'Русский',
		newsForTheYear: 'News for the {0} year',
		releaseHistory: 'Release history',
		result: 'Result',
		screenshots: 'Screenshots',
		selectExample: 'Select an example…',
		selectFile: 'Select file…',
		spardTableDescription: 'This transformer works with SPARD subset - SPARD Lite which includes symbols, strings and operators |, _, $, :: и =>.',
		spardTableHint: 'Is is equal to the classic (tree-based) SPARD-transformer but has a bigger performance. But additional time for building it is required.',
		spardTableTransformer: 'SPARD table transformer',
		spardTransformer: 'SPARD transformer',
		tableTransform: 'Table transform',
		tags: 'Tags',
		transform: 'Transform',
		transformationRules: 'Transformation rules (SPARD)',
		transformationRulesLight: 'Transformation rules (SPARD Lite)',
		transformationTime: 'transformation time',
		tvGamesHeader: 'TV Game Computer Analogues (Russian)',
		tvGameSvoyaIgra: 'Computer "Svoya Igra" by Maxim Kishkevich (Russian)',
		tvGameChgkDf: '"What? Where? When?" by Danil Fedorovih (Russian)',
		tvGameMillionTvgame: 'Multiple versions of "Who Wants to Be a Millionaire?" (Russian)',
		tvGameSlaboeZvenoApteka: '"Weakest Link" by Multifox (Alexey Romanov) (Russian)',
		tvGameRussianRoulette: 'Computer game "Russian Roulette" by Sergey Boytsov & Co (Russian)',
		tvGamePoleChudesOnline: 'Online game "Field of Miracles" (Russian)',
		tvGameUgadajMelodiju: 'Computer game "Guess the Melody" by Dmitry Sharov (Russian)',
		tvGameMillionOhLucky: '"Who Wants to Be a Millionaire?" (unknown author) (Russian)',
		tvGameMillionErudit: '"Who Wants to Be a Millionaire?" by L.I. Fedorchuk (Russian)',
		tvGameMillionOhLucky2: '"Who Wants to Be a Millionaire?" by Vladimir Khil (Russian)',
		tvGameTheSmartest: '"Who is the Smartest?" by comulti multimedia (Russian)',
		upload: 'Upload…',
		version: 'Version',
		webBrowser: 'Web browser',
		websiteNews: 'Website news',
		aboutTheAuthor: 'About the Author',
		aboutMyself: 'Vladimir Khil',
		aboutMyselfText: 'Hi! I\'m a passionate software developer and mathematician who loves creating innovative solutions. I specialize in building applications that make complex tasks simple and enjoyable.',
		experienceText: 'I work primarily with .NET technologies and have extensive experience in C#, TypeScript, and modern web development. I enjoy working on everything from desktop applications to web platforms, always focusing on clean code and great user experiences.',
		educationText: 'I graduated with honors from MAI (Moscow Aviation Institute) with degrees in mathematics and computer science.',
		projectsText: 'I\'ve created various projects including quiz games, language processing tools, and educational applications. I also developed my own programming language called SPARD for text transformations.',
		currentPositionText: 'Currently working as a team lead, helping teams build amazing software while continuing to code and learn new technologies.',
		githubProfile: 'View my projects on GitHub',
		donateTitle: 'Support My Work',
		donateExplanation: 'I\'m developing SIGame and related projects, and also spend my own money to support the game server and domain. Your support helps me continue creating and maintaining these free tools for the community.',
		donatePatreonDescription: 'Support my ongoing development work with monthly contributions. Get access to exclusive updates and early previews of new features.',
		donateBoostyDescription: 'Support me on the Russian platform Boosty with flexible payment options and exclusive content for subscribers.',
		donateYooMoneyDescription: 'Make a one-time donation via YooMoney to help cover server costs and development expenses.',
		donateSupport: 'Support via',
		donateThankYou: 'Thank you for your support! Every contribution helps me dedicate more time to improving SIGame and creating new features.',
	},
	ru: {
		andLater: 'и выше',
		blog: 'Блог',
		buildTransformTable: 'Составить таблицу переходов',
		classicTransform: 'Классическое преобразование',
		details: 'Описание',
		hint: 'На этой странице можно осуществить преобразование входного текста в соответствии с заданными правилами преобразования (на языке SPARD).',
		inputText: 'Входной текст',
		install: 'Установить',
		isClassicResultNotTheSame: 'классический преобразователь дал другой результат',
		familyNotFound: 'Приложение не найдено',
		files: 'Файлы',
		friendLinkAlexandrProsvirnov: 'Александр Просвирнов о своём участии в «Своей игре»',
		friendLinkAlexUtah: '«Своя игра» глазами Александра Успанова',
		friendLinkGameShows: 'GameShows — Всё о телеиграх',
		friendLinks: 'Дружественные ссылки',
		friendLinkSI: '«Своя игра»: база данных игроков и игр, история и статистика',
		isClassicResultTheSame: 'классический преобразователь дал такой же результат',
		generateSourceCode: 'Создать код',
		home: 'Главная',
		knownIssues: 'Известные проблемы и решения',
		languageEn: 'English',
		languageRu: 'Русский',
		newsForTheYear: 'Новости за {0} год',
		releaseHistory: 'История версий',
		result: 'Результат',
		screenshots: 'Галерея',
		selectExample: 'Выберите пример…',
		selectFile: 'Выберите файл…',
		spardTableDescription: 'Преобразователь работает на подмножестве SPARD - SPARD Lite, включающем в себя символы, строки и операции |, _, $, :: и =>.',
		spardTableHint: 'Аналогичен классическому (древовидному) SPARD-преобразователю, но работает более эффективно. При этом затрачивается дополнительное время на его построение.',
		spardTableTransformer: 'Табличный преобразователь SPARD',
		spardTransformer: 'Преобразователь SPARD',
		tableTransform: 'Табличное преобразование',
		tags: 'Теги',
		transform: 'Преобразовать',
		transformationRules: 'Правила преобразования (SPARD)',
		transformationRulesLight: 'Правила преобразования (SPARD Lite)',
		transformationTime: 'время преобразования',
		tvGamesHeader: 'Компьютерные аналоги телевизионных игр',
		tvGameSvoyaIgra: 'Компьютерная «Своя игра» (автор — Максим Кишкевич)',
		tvGameChgkDf: '«Что? Где? Когда?» (автор — Данил Фёдоровых)',
		tvGameMillionTvgame: 'Множественные версии «Кто хочет стать миллионером?»',
		tvGameSlaboeZvenoApteka: '«Слабое звено» от Multifox (Алексей Романов)',
		tvGameRussianRoulette: 'Компьютерная игра «Русская рулетка» (автор - Сергей Бойцов и Ко)',
		tvGamePoleChudesOnline: 'Онлайн-игра «Поле Чудес»',
		tvGameUgadajMelodiju: '«Угадай мелодию» (автор — Дмитрий Шаров)',
		tvGameMillionOhLucky: '«Кто хочет стать миллионером?» (автор неизвестен)',
		tvGameMillionErudit: '«Кто хочет стать миллионером?» (автор — Л.И. Федорчук)',
		tvGameMillionOhLucky2: '«Кто хочет стать миллионером?» (автор — Владимир Хиль)',
		tvGameTheSmartest: '«Кто самый умный?» от comulti multimedia',
		upload: 'Загрузить…',
		version: 'Версия',
		webBrowser: 'Веб-браузер',
		websiteNews: 'Новости сайта',
		aboutTheAuthor: 'Об авторе',
		aboutMyself: 'Владимир Хиль',
		aboutMyselfText: 'Привет! Я увлеченный разработчик программного обеспечения и математик, который любит создавать инновационные решения. Специализируюсь на создании приложений, которые делают сложные задачи простыми и приятными.',
		experienceText: 'Работаю преимущественно с технологиями .NET и имею обширный опыт в C#, TypeScript и современной веб-разработке. Мне нравится работать над всем — от настольных приложений до веб-платформ, всегда фокусируясь на чистом коде и отличном пользовательском опыте.',
		educationText: 'Окончил с отличием МАИ (Московский авиационный институт) по специальностям математика и информатика.',
		projectsText: 'Создал различные проекты, включая викторины, инструменты обработки языков и образовательные приложения. Также разработал собственный язык программирования SPARD для трансформации текстов.',
		currentPositionText: 'В настоящее время работаю тимлидом, помогая командам создавать удивительное программное обеспечение, продолжая при этом программировать и изучать новые технологии.',
		githubProfile: 'Посмотреть мои проекты на GitHub',
		donateTitle: 'Поддержите мою работу',
		donateExplanation: 'Я разрабатываю SIGame и связанные проекты, а также трачу собственные средства на поддержку игрового сервера и домена. Ваша поддержка помогает мне продолжать создавать и поддерживать эти бесплатные инструменты для сообщества.',
		donatePatreonDescription: 'Поддержите мою работу с помощью ежемесячных взносов. Получите доступ к эксклюзивным обновлениям и ранним превью новых функций.',
		donateBoostyDescription: 'Поддержите меня на российской платформе Boosty с гибкими вариантами оплаты и эксклюзивным контентом для подписчиков.',
		donateYooMoneyDescription: 'Сделайте разовое пожертвование через YooMoney, чтобы помочь покрыть расходы на сервер и разработку.',
		donateSupport: 'Поддержать через',
		donateThankYou: 'Спасибо за вашу поддержку! Каждый вклад помогает мне уделять больше времени улучшению SIGame и созданию новых функций.',
	}
},
{
	customLanguageInterface: getCulture
});

export default localization;
