apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personal-site.fullname" . }}
  labels:
    {{- include "personal-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "personal-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "personal-site.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "personal-site.fullname" . }}
        - name: nginx
          configMap:
            name: {{ include "personal-site.fullname" . }}-nginx
            defaultMode: 0664
        - name: nginx-default
          configMap:
            name: {{ include "personal-site.fullname" . }}-nginx-default
            defaultMode: 0664
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-default
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:{{ .Values.nginxPrometheusExporter.tag }}
          args:
            - '-nginx.scrape-uri=http://localhost:{{ .Values.service.targetPort }}/metrics'
          resources:
            {{- toYaml .Values.nginxPrometheusExporter.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.nginxPrometheusExporter.port }}
